#!/bin/bash

echo "🚀 Setting up Automated Backtest System for All Agents"
echo "======================================================"
echo ""

echo "📋 STEP 1: Apply Database Migrations"
echo "-----------------------------------"
echo "Please run the following SQL commands in your Supabase SQL Editor:"
echo ""
echo "-- First, apply the subscription schema fix (if not already done):"
echo ""
cat fix-subscriptions-schema.sql
echo ""
echo "-- Then, apply the backtest history table:"
echo ""
cat apply-backtest-history-migration.sql
echo ""
echo "⚠️  Press Enter after you've applied both migrations..."
read

echo ""
echo "📋 STEP 2: Test the Enhanced Backtest System"
echo "--------------------------------------------"
echo "The enhanced backtest system now:"
echo "✅ Runs backtests for multiple periods (1y, 2y, 5y) for all agents"
echo "✅ Stores results in agent_backtest_history table"
echo "✅ Provides fallback to real-time backtests if no historical data exists"
echo "✅ Updates live performance section on agent detail pages"
echo ""

echo "📋 STEP 3: Run Backtests for All Agents"
echo "---------------------------------------"
echo "To run backtests for all agents, you can:"
echo ""
echo "Option A - Via API (if you have CRON_SECRET set):"
echo "curl -X POST 'http://localhost:3000/api/cron/run-backtests' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -H 'x-cron-secret: YOUR_CRON_SECRET' \\"
echo "  -d '{}'"
echo ""
echo "Option B - Via agent detail page 'Refresh' button:"
echo "1. Visit any agent page (e.g., http://localhost:3000/agents/sol-breakout)"
echo "2. Click the refresh button in the Backtest tab"
echo "3. This will run backtests for that specific agent"
echo ""

echo "📋 STEP 4: Verify Live Performance Data"
echo "----------------------------------------"
echo "After running backtests, check the agent detail pages:"
echo "1. Visit http://localhost:3000/agents/sol-breakout"
echo "2. Click on the 'Performance' tab"
echo "3. You should see 'LIVE PERFORMANCE - PAST RESULTS' section with:"
echo "   - 5 YEARS data"
echo "   - 2 YEARS data" 
echo "   - 1 YEAR data"
echo ""

echo "📋 STEP 5: Automated Scheduling (Optional)"
echo "-----------------------------------------"
echo "To schedule automatic backtest runs, set up a cron job:"
echo ""
echo "# Run backtests every 6 hours"
echo "0 */6 * * * curl -X POST 'https://your-domain.com/api/cron/run-backtests' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -H 'x-cron-secret: YOUR_CRON_SECRET' \\"
echo "  -d '{}'"
echo ""

echo "✅ Setup Complete!"
echo ""
echo "Summary of what was implemented:"
echo "• Enhanced backtest API to run multiple periods (1y, 2y, 5y)"
echo "• Created agent_backtest_history table for historical data storage"
echo "• Updated live performance UI to use historical data"
echo "• Added fallback to real-time backtests when needed"
echo "• Maintained backward compatibility with existing systems"
echo ""
echo "🎯 New agents will automatically get backtest data when:"
echo "• They have primary_symbol and backtest_strategy configured"
echo "• The cron job runs or someone triggers the backtest"
echo "• The live performance section will show data for all time periods"
