name = "ase-cron"
main = "src/index.ts"
compatibility_date = "2026-03-24"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["* * * * *"]

[vars]
# URL of the deployed Next.js app (the main "ase" worker)
NEXT_PUBLIC_APP_URL = "https://ase.jazing14.workers.dev"

CRON_SECRET = "9f3c2b7a1e8d4c6f0a2b9e7d1c4f8a6b"