/// <reference types="@cloudflare/workers-types" />

/**
 * ASE Cloudflare Worker — entry point
 *
 * Wraps the OpenNext-generated Next.js worker and adds a scheduled cron
 * handler so the trading agents run inside the same single deployment.
 *
 * Build order (handled by `npm run deploy`):
 *   1. `opennextjs-cloudflare build`  → produces .open-next/worker.js
 *   2. `wrangler deploy`              → bundles this file (imports .open-next/worker.js)
 */

// @ts-expect-error: generated by `npm run cf:build` — not present before build
import openNextWorker from '../.open-next/worker.js'

// Re-export Durable Objects that OpenNext registers on the worker
// (needed for ISR tag-cache, queue handler, and R2 cache purge)
// @ts-expect-error: generated file
export { DOQueueHandler } from '../.open-next/worker.js'
// @ts-expect-error: generated file
export { DOShardedTagCache } from '../.open-next/worker.js'
// @ts-expect-error: generated file
export { BucketCachePurge } from '../.open-next/worker.js'

interface Env {
  CRON_SECRET?: string
  NEXT_PUBLIC_APP_URL?: string
  [key: string]: unknown
}

export default {
  // ── HTTP: pass every request straight through to Next.js ────────────────
  fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    return openNextWorker.fetch(request, env, ctx)
  },

  // ── Cron: fires every minute (see wrangler.jsonc triggers) ──────────────
  async scheduled(event: ScheduledEvent, env: Env, ctx: ExecutionContext): Promise<void> {
    const secret = env.CRON_SECRET ?? ''
    const headers: Record<string, string> = {
      'x-cron-secret': secret,
      'content-type': 'application/json',
    }

    console.log(`[cron] tick — ${new Date().toISOString()}`)

    // ── Run all 5 trading strategies ──────────────────────────────────────
    // Calls POST /api/cron/run-agents internally through the Next.js handler.
    // Using a fake host — Next.js routes by path, host doesn't matter.
    try {
      const res = await openNextWorker.fetch(
        new Request('https://worker.internal/api/cron/run-agents', {
          method: 'POST',
          headers,
        }),
        env,
        ctx,
      )
      const body = await res.json().catch(() => null)
      console.log(`[cron] run-agents → ${res.status}`, JSON.stringify(body))
    } catch (err) {
      console.error('[cron] run-agents failed:', err)
    }

    // ── Update NAV every 5 minutes ────────────────────────────────────────
    if (new Date().getMinutes() % 5 === 0) {
      try {
        const res = await openNextWorker.fetch(
          new Request('https://worker.internal/api/cron/update-nav', {
            method: 'POST',
            headers,
          }),
          env,
          ctx,
        )
        const body = await res.json().catch(() => null)
        console.log(`[cron] update-nav → ${res.status}`, JSON.stringify(body))
      } catch (err) {
        console.error('[cron] update-nav failed:', err)
      }
    }
  },
}
